
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.Scanner;
import org.junit.Test;
import static org.junit.Assert.*;

public class HangmanTest {
    
    @Test
    public void userInput_forGettingUserInput() {
        //Test to see if the user input is being taken in.
        Hangman testHangman = new Hangman();
        Scanner expected = new Scanner(System.in);
        assertEquals(expected, testHangman.userInput(expected)); 
    }
}
