
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;

public class HangmanTest {
    // List<String> hangmanWords = Arrays.asList("word", "computer", "batman", "superman");
    // Random generateWord = new Random();

    // String guessWord = hangmanWords.get(generateWord.nextInt(hangmanWords.size()));

    @Test
    public void findWord_forWordsInArray() {
        Hangman testHangman = new Hangman();
        String expected = guessWord;
        hangmanWords.contains(guessWord);
        assertEquals(expected, testHangman.findWord(guessWord));
    }

    @Test
    public void findWord_forReplacingLettersOfWordsInArray() {
        Hangman testHangman = new Hangman();
        String expected = ("----");
        assertEquals(expected, testHangman.findWord("word"));
    }
}
